In [1]:
l = [10,20,50,120,130,5,150,200]

In [2]:
import numpy as np

In [3]:
dir(l)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

#### Min

In [4]:
np.min(l)

np.int64(5)

#### Max

In [5]:
np.max(l)

np.int64(200)

#### Mean(mu)

In [6]:
np.mean(l)

np.float64(85.625)

#### Median

In [7]:
np.median(l)

np.float64(85.0)

In [8]:
np.mode(l)

AttributeError: module 'numpy' has no attribute 'mode'

#### Varience

In [9]:
np.var(l)

np.float64(4771.484375)

In [10]:
# steps to calculate varience

# var = (summation(x-mean)^2)/total no. of values(N)

# 1. raw data (x)
# 2. mean(mu)
# 3. x-mu
# 4. (x-mu)^2
# 5. summation((x-mu)^2)
# 6. summation((x-mu)^2)/total no. values(N)


In [11]:
l = [10,20,50,120,130,5,150,200] 
arr = np.array(l)                # 1
mean = np.mean(l)
dev = arr - mean 
sq = np.square(dev)
summ = np.sum(sq)
var = summ/len(l)

var

np.float64(4771.484375)

In [12]:
np.sum(np.square(arr-mean))/len(l)

np.float64(4771.484375)

In [13]:
np.sum(np.square(np.array(l)-np.mean(l)))/len(l)

np.float64(4771.484375)

#### Standard Deviation

In [14]:
np.std(l)

np.float64(69.07593195172976)

In [15]:
np.sqrt(var)

np.float64(69.07593195172976)

In [16]:
np.sqrt(np.sum(np.square(np.array(l)-np.mean(l)))/len(l))

np.float64(69.07593195172976)

#### Covarience

In [17]:
np.cov(l)

array(5453.125)

In [34]:
l1 = [10,20,50,120,130,5,150,200]
l2 = [2,3,5,9,10,30,40,50]

arr1 = np.array(l1)
arr2 = np.array(l2)

In [38]:
# Covarience = sum((x-x_mean)(y-y_mean))/(n-1)

cov = np.sum((arr1-np.mean(arr1))*(arr2-np.mean(arr2)))/(len(l1)-1)
cov

np.float64(871.6964285714286)

In [36]:
np.cov(arr1,arr2)

array([[5453.125     ,  871.69642857],
       [ 871.69642857,  349.125     ]])

#### Correlation

In [18]:
np.corr(l)    # It will not work on one variable means it will not work on one lis it will need two lists.

AttributeError: module 'numpy' has no attribute 'corr'

In [39]:
# Correlation = cov(x,y)/std(x)*std(y)

corr = np.cov(arr1,arr2)/(np.std(arr1)*np.std(arr2))
corr

array([[4.51673072, 0.72201133],
       [0.72201133, 0.2891743 ]])

In [45]:
corr = np.cov(arr1,arr2)/(np.std(arr1)*np.std(arr2))
corr

array([[4.51673072, 0.72201133],
       [0.72201133, 0.2891743 ]])

In [49]:
# np.sum((arr1-np.mean(arr1))*(arr2-np.mean(arr2)))/(np.sum(np.square(arr1-np.mean(arr1)))*(np.sum(np.square(arr2-np.mean(arr2)))))

In [48]:
# corr = np.sum((arr1-np.mean(arr1)*(arr2-np.mean(arr2)))((np.sum(np.square(arr1-np.mean(arr1)))/len(arr1))*(np.sum(np.square(arr2-np.mean(arr2)))/len(arr2)))
# corr

In [19]:
# range = max-min
range = np.max(l) - np.min(l)
range

np.int64(195)

In [ ]:
# IQR = Q3 - Q1



In [21]:
np.count_nonzero(l)

np.int64(8)

#### Percentile

In [22]:
np.percentile(l,50)   # It will give the 50 percentile of the given list.

np.float64(85.0)

In [23]:
np.percentile(l,25)  # It will give the 25 percentile of the given list.

np.float64(17.5)

In [24]:
np.percentile(l,75) # It will give the 75 percentile of the given list.

np.float64(135.0)

#### Quartile

In [25]:
np.quantile(l,0.25)   # It will give quantile1(Q1) of the given list

np.float64(17.5)

In [26]:
np.quantile(l,0.5)   # It will give quantile2(Q2) of the given list

np.float64(85.0)

In [28]:
np.quantile(l,0.75)  # It will give quantile3(Q3) of the given list

np.float64(135.0)

In [27]:
# By observing above percentile and quantile we can say that percentile(x) = quantile(0.x)